### ISSUE TITLE
Promotion - utiliser les multiple de quantité associé

### ISSUE THREAD

**Issue by julienbourdeau** [julienbourdeau/PiggyBox#109]
Lorsque l'on fait une promo on met une quantite associé.
Si le client prend cette quantite il beneficie de la promo. 
## Par exemple
- 1 pour 2 euros
- 3 pour 5 euros (au lieu de 6)

Le script detecte la quantite et affiche le bon prix. Il faudrait utiliser tous les multiples. C'est a dire _6 pour 10 euros_
A l'heure actuel c'est 6 pour 12 euros

**Comment by dupuchba** [comment]
@julienbourdeau Tu considères cela urgent? Je peux le faire mais je regarde si il y'a pas des PR plus urgentes
